name: Lint Test Deploy
on: push
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Setup Node js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm i
      - name: Run Linting
        run: npm run lint
      - name: Run Tests
        run: npm test
      - name: Build App
        run: npm run build
  deploy:
    needs: testAndBuild
    runs-on: ubuntu-latest
    steps:
      - name: Deployment
        run: echo "deploying..."
